version: '3.8'

services:

  vk-db-exporter:
    container_name: vk-db-exporter
    image: prom/mysqld-exporter
    environment:
      DATA_SOURCE_NAME: "exporter-user:0000@(db:6633)/"
    ports:
      - "9104:9104"

  prometheus:
    container_name: prometheus
    image: prom/prometheus
    ports:
      - "11820:9090"
    volumes:
      - ./resources/prometheus/prometheus.yml:/etc/prometheus/prometheus.yml

  grafana:
    container_name: grafana
    image: grafana/grafana
    ports:
      - "3000:3000"

  loki:
    container_name: loki
    image: grafana/loki:2.9.1
    volumes:
      - ./resources/loki:/mnt/config
    command: -config.file=/mnt/config/loki-config.yaml
    ports:
      - "3100:3100"
