server:
  port: 11801


spring:
  datasource:
    driver-class-name: org.mariadb.jdbc.Driver
    url: jdbc:mariadb://127.0.0.1:11810/db
    username: root
    password: '0000'

  jpa:
    hibernate:
      ddl-auto: none