server:
  port: 11801
  tomcat:
    basedir: ./app/auth-api
    accesslog:
      enabled: true
      directory: logs
      suffix: .log
      prefix: access_log
      file-date-format: .yyyy-MM-dd
      pattern: "%{yyyy-MM-dd HH:mm:ss}t %s %r %{User-Agent}i %{Referer}i %a %b"

spring:
  datasource:
    driver-class-name: org.mariadb.jdbc.Driver
    url: jdbc:mariadb://soa-db:3306/db
    username: root
    password: '0000'

  jpa:
    hibernate:
      ddl-auto: none


management:
  endpoints:
    web:
      exposure:
        include: prometheus, metrics