global:
  scrape_interval: 15s

scrape_configs:
  - job_name: auth-api
    metrics_path: '/actuator/prometheus'
    static_configs:
      - targets: [ 'host.docker.internal:11801' ]
  - job_name: order-api
    metrics_path: '/actuator/prometheus'
    static_configs:
      - targets: [ 'host.docker.internal:11802' ]